name: conda-recipe-manager
channels:
  - defaults

# TODO Future: break-up dev dependencies into a separate environment file.
dependencies:
  - black
  - isort
  - make
  - mypy
  - python >=3.11
  - pytest ==9.0.2
  - pytest-cov
  - pytest-socket >=0.7.0
  - pytest-xdist
  - pyfakefs >=6.0.0
  # Match version with .pre-commit-config.yaml to ensure consistent rules with `make lint`.
  - pylint ==4.0.4
  - pip
  - click 8.2.1
  - conda
  - evalidate >=2.0.3,<3.0.0
  - jinja2
  - pyyaml
  - types-pyyaml
  - jsonschema
  - types-jsonschema
  - requests
  - types-requests
  - gitpython
  - pre-commit
  # NOTE: As of 2026-02-25, we no longer install documentation dependencies for all development environments.
  # We install them as needed through `make docs`.
